import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import RandomText from '../features/randomtext/randomText'
import Settings from '../features/setup/setup'
import Score from '../features/score/score'
import styles from '../styles/Home.module.css'

import { Container, Card, Row, Col, Text, Grid } from "@nextui-org/react";


const Home: NextPage = () => {
  return (
    <Container justify="center">
      <Head>
        <title>Typing Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Typing Challenge!
        </h1>

        {/* <p className={styles.description}>
          Get started by generating a random text or copy/paste your own text!
        </p> */}
        <Card className={styles.description} css={{ $$cardColor: '$colors$primary' }}>
        <Card.Body>
          <Row justify="center" align="center">
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              Get started by generating a random text or copy/paste your own text!
            </Text>
          </Row>
        </Card.Body>
      </Card>

      <Grid.Container gap={2} justify="center">

        <Grid id={styles.setting} xs={12} sm={4}>
          <Settings/>
        </Grid>
        <Grid id={styles.score}  xs={6} sm={4}>
          <Score />
        </Grid>
        <Grid id={styles.timer}  xs={6} sm={4}>
          <Text>Timer</Text>
        </Grid>
      </Grid.Container>
        
        
        <Card >
          <Card.Body>
              <RandomText />
          </Card.Body>
        </Card>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      </Container>
  )
}

export default Home
