import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Type Along</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Type Along!
        </h1>

        <p className={styles.description}>
          Get started by generating a random text or copy/paste your own text!
        </p>

        <div className={styles.grid}>
          <div id={styles.text_source}>
            <textarea id="main-text" name="main_text" rows={10} cols={50} maxLength={200}>
              A nice day is a nice day.
              Lao Tseu
            </textarea>
            <button id={styles.generate_button}>Generate text</button>
          </div>
        

        <textarea id="type-along" name="typealong" rows={10} cols={50} maxLength={200}>
            A nice day is a nice day.
            Lao Tseu
        </textarea>
         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
